### PR TITLE
LPS-85711 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-85711

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @pavel-savinov the issue with name not being entered was because of a test fix I forgot to account for when making the first set of fixes. (Need to select the correct iframe before we can find the locator). However, there is still the issue of Global Page Templates redirecting to the "Edit" mode (being able to add widgets) vs "Configure" mode (being able to change name, and toggle things like "Show in Public Pages Hierarchy Menu"). However if this change is intentional, please let me know and I can make the appropriate test fixes! Sorry that this is taking a while, we just don't want to risk any bugs getting in / too many tests breaking! Let me know if you have any questions!

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/197. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/96. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63838. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63840. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/1fa01ce~1...1fa01ce) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63849. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/2cd574d~2...2cd574d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
