### PR TITLE
LPS-88426 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-88426

### CODE REVIEW

**Comment by kyle-miho** [comment]
fowarded here: https://github.com/pavel-savinov/liferay-portal/pull/278

**Comment by kyle-miho** [comment]
cc @ealonso @p2kmgcl @sandrodw3 @jkappler

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/227. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
