### PR TITLE
LPS-96828 Fix imports

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Hi @pavel-savinov I tested the fix and while now the non-instanceable portlets are available in experiences (even if the portlet has been added to other experience), when dragging and dropping them into the page I get the error:

`Cannot add non-instanceable portlet more than once`

See AddPortletMVCActionCommand#125. 

I had to rebase and fix some conflicts during my review. Maybe this has to do with the issue. 

Thanks!

**Comment by epgarcia** [comment]
@pavel-savinov Source formatting points that for..of loops are not allowed (see FragmentsEditorUpdateUtils.es.js#342)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75839. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/0d1a8f2036b1~3...0d1a8f2036b1)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75847. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/9adf22ace2a0~4...9adf22ace2a0)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75849. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/621827667c7e~4...621827667c7e)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75850. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/621827667c7e~4...621827667c7e)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/858. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/621827667c7e~4...621827667c7e)

**Pull request closed without merging**
