### PR TITLE
LPS-79348

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hi @pavel-savinov 
Do we have some updates for this pull reuqest?

**Comment by pavel-savinov** [comment]
@arthurchan35 I will take care of it today. Thanks!

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57310. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
