### PR TITLE
LPS-33201 Track embedded portlets to prevent infinite loop

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Pavel! I was exploring if one of our new frameworks could assist the fixing of LPS-33201. Unfortunately that was a dead end, but I was able to resolve the issue differently and @topolik agrees on the approach. Please can you review?

p.s. I notice that "null" is shown instead of a useful error message when an embedding loop is detected.

/cc @juliocamarero

### CODE REVIEW

**Comment by juliocamarero** [comment]
@jkappler can you please have a look at this pull? thanks!

**Comment by jkappler** [comment]
Hi @stian-sigvartsen, just one question. We can have a scenario where a customer would want to embed a portlet without instance in the theme twice. For example the same site navigation portlet in the header and in the footer. Now it works and when configuring, both have the same configuration.

How would it work in this case? Or is this a scenario that we are not going to support anymore? Let me know what you think.

Thanks

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by stian-sigvartsen** [comment]
@jkappler this should still work because I used a stack and the embedding is like depth first traversal of a tree of portlet IDs. When moving up the tree (after completing a sub-branch), portlet IDs are removed from the stack. In the scenario you described portlets embedded in the header and footer are like sibling nodes within this tree and consequently will not find each other in the stack.

Also I used a ThreadLocal to store the stacks, which should ensure that if multiple threads are used to process the portlets for a particular request, they will not have any kind of race condition and occasionally falsely report embedding loops in your scenario and others.

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40402. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
