### PR TITLE
LPS-99643 DuplicateDiscussionHelper to duplicate the disscussion

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
cc/ @4lejandrito

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77332. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/1afc410f2fc0~4...1afc410f2fc0)

**Pull request closed without merging**
