### PR TITLE
LPS-107688 Set fragmentContentFields in FragmentDefinition

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Depends on https://github.com/brianchandotcom/liferay-portal/pull/84321

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/169. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/17bc020abf88~1...17bc020abf88)

**Pull request closed without merging**
