### PR TITLE
LPS-80757 New upgrade process for images that are created in 7.0.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59057. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/0b040f1~1...0b040f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59058. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/beab471~2...beab471) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
