### PR TITLE
LPS-85203 Starting level of navigation cannot be configured in Navigation portlet

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/62. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/9808a26~5...9808a26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
