### PR TITLE
LPS-95349 reference order changed, Layout becomes after LayoutPrototype

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:staging

**Comment by zoltancsaszi** [comment]
Hey @pavel-savinov ,

I changed the order of the references. Was it intended to add the Layouts first or doesn't matter?
I hope it won't cause any other regressions.

Could you check it, please?

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73091.

**Pull request closed without merging**
