### PR TITLE
LPS-110725 Check if we are displaying a conversion layout, if so not do not get the published layout as it is of type portlet

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@pavel-savinov it's just waiting on one upgrade test to run, hasn't even started (CI is too backed up right now).
5 other upgrade tests already passed, so unless you're concerned about upgrades for this change, it's probably ready to send to Brian.

**Pull request closed without merging**
