### PR TITLE
LPS-105745

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @pavel-savinov,

Attached is an update for http://issues.liferay.com/browse/LPS-105745.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Hey @jonmak08,
this pull still has rebase conflicts, and even resolving them on current Master in looks weird on hover:
Screenshot 2019-12-19 at 11 53 39

**Comment by katienesterovich** [comment]
Hey @pavel-savinov, 
For some reason I'm not seeing that in Chrome or Firefox on the latest hash (1aab1cd79c35bef0781f5f2095c6928243d0be16). Can you let me know where exactly you're inspecting the button. Perhaps I'm missing something.

**Comment by jonmak08** [comment]
Hey @pavel-savinov,

I fixed the rebase error and force pushed to this branch.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Hi @pavel-savinov,

I am not seeing the hover issue you stated either.  I have attached a screencast of what I saw when I deployed the changes.

master

Please let me know if you have any questions. Thanks!

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82397.

**Pull request closed without merging**
