### PR TITLE
LPS-100615 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-100615

### CODE REVIEW

**Comment by kyle-miho** [comment]
@pavel-savinov The user does not exist issue is fixed, but theres an NPE with the main renderer now. some changes have been updated to upstream since you tested it

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77711. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/9ee4d14fe6d2~2...9ee4d14fe6d2)

**Pull request closed without merging**
