### PR TITLE
LPS-108805

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:upgrade

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85714.

**Comment by csierra** [comment]
hi @Preston-Crary, 
wouldn't this still block the upgrade thread eventually?

Thx!

Carlos.

**Comment by Preston-Crary** [comment]
Hi @csierra,

I think it won't because of eddb23b013fa4f2007a0fd72edd2131ad2d7f422.  This makes it so that the view count upgrade must be run and the view count service is activated before the fragement upgrade since the view count service is a reference of the fragement upgrade.  There is a chance there's still a race condition since we're using a portal service in the upgrade, but it's much less likely.

**Comment by ricardocousolr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
