### PR TITLE
LPS-102820 Add portlet language key, and copy over other languages keys that are needed from layouts admin portlet

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/243. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/84f983b7c119~1...84f983b7c119)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79295. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/84f983b7c119~1...84f983b7c119)

**Pull request closed without merging**
