### PR TITLE
LPS-88477

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:help

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
i will resend

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66110. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
