### PR TITLE
LPS-89373 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-89373

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
retesting due to ci instability

**Comment by kyle-miho** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67460.

**Pull request closed without merging**
