### PR TITLE
LPS-106514 Don't show the the plus button for content pages and display pages

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2692. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/59666bc83971~1...59666bc83971)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/495. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/a2cbab1665e0~1...a2cbab1665e0)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/497. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/2a53ee3aad3a~2...2a53ee3aad3a)

**Pull request closed without merging**
