### PR TITLE
LPS-107012

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84192

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84217. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/158105090156~1...158105090156)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84223. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/7c79e3e16344~1...7c79e3e16344)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84224. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/c7562edc78c7~1...c7562edc78c7)

**Pull request closed without merging**
