### PR TITLE
LPS-88499

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66200 thx.

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66206. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/4d8940f~1...4d8940f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66207. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/e4e2b25~2...e4e2b25) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
