### PR TITLE
LPS-105745

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @pavel-savinov,

Attached is an update for http://issues.liferay.com/browse/LPS-105745.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Hey @jonmak08, @katienesterovich,
Could you please take a look and clarify what do you want to achieve with this change?
Here are the screenshots of the current Master using this PR:
Screenshot 2019-12-18 at 15 48 38
and with Discard button hovered:
Screenshot 2019-12-18 at 15 49 21

Thanks!

**Comment by katienesterovich** [comment]
Hey @jonmak08 @pavel-savinov,

I am able to reproduce part of this behavior if I apply 57d789075c929765469a039b0936341782a6876a. 
(I am hovering over Discard Draft here in default theme)
Screen Shot 2019-12-18 at 10 40 42 AM

If I move `background-colof: #fff` back to `button.btn-secondary`, I am not seeing this issue. However, the color of the button does not change on hover. 
(I am hovering over Discard Draft here in default theme). 
Screen Shot 2019-12-18 at 10 43 41 AM

**Comment by jonmak08** [comment]
Hey @katienesterovich,

I added https://github.com/pavel-savinov/liferay-portal/commit/57d789075c929765469a039b0936341782a6876a, since the default text color for the button is `#6b6c7e` in clay, but after reviewing it closer, I found that only `btn-secondary`'s color is set to `#6b6c7e`.  We can remove my source formatting change.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/pavel-savinov/liferay-portal/pull/476

**Comment by katienesterovich** [comment]
Hi @jonmak08,
No worries, thanks for the clarification :)

**Pull request closed without merging**
