### PR TITLE
LPS-90108 Next item if we already modified the record

### PR DESCRIPTION
**Pull request by achaparro**
Hi @pavel-savinov,

I have realized that there was a bug reusing friendlyURLs in the method _updateFriendlyURLEntryLocalizations, that caused the test to fail. I have solved it with these changes.

I think it's better to solve in FriendlyURLEntryLocalServiceImpl since in this way will be fixed for other components using the friendlyURL framework.

Let's wait for the final result of the tests.

Cheers.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68022.

**Pull request closed without merging**
