### PR TITLE
LPS-100777 Missing or wrong permission checks in Fragments services

### PR DESCRIPTION
**Pull request by topolik**
Hi Pavel,

I made some changes, can you please review them and test?

One more question, should Fragments honor staging? If so we might need to add StagedModelPermissionLogic (e.g. see here: https://github.com/liferay/liferay-portal/blob/b25b56ea059f2b8cc29d4aa52ff8c8a1a5adbdd1/modules/apps/bookmarks/bookmarks-service/src/main/java/com/liferay/bookmarks/internal/security/permission/resource/BookmarksEntryModelResourcePermissionRegistrar.java#L64)

Thank you.

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by topolik** [comment]
@pavel-savinov do you want me to fix the tests or are you going to do it yourself?

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/803. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/18906b923643~1...18906b923643)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
