### PR TITLE
LPS-91279 Replace "." with "_" in temporary variable names in the date field template

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Hi @vendeltoreki, it would be much better to fix this on the DDM side because now DDM TemplateHandler generates nested variables names using period instead of underscore.

**Comment by vendeltoreki** [comment]
Hi @pavel-savinov ,

I think the ${name} variable is generated correctly with "." on the DDM side in [this code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/template/BaseDDMTemplateHandler.java#L96), since the data itself can be reached like `ParentEntry.ChildEntry.getData()`. It is also used in [init.ftl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/com/liferay/journal/web/portlet/template/dependencies/init.ftl#L3).
The only problem is the temporary variable, that the Date type pattern uses, e.g.: `ParentEntry.ChildEntry_Data`, which is generated this way: `${name}_Data`.

It might be a solution to introduce another variable for temporary variable names on DDM side (something, like: `tempVarName = "ParentEntry_ChildEntry"`), so all other templates could use it. As I see, Date and [geolocation](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/com/liferay/journal/web/portlet/template/dependencies/geolocation.ftl#L17) types also use `${name}` in variable names.

**Comment by vendeltoreki** [comment]
Hi @pavel-savinov ,

I tried a change on DDM side: generate ${name} variable with underline ("_") instead of the period, and the final FTL rendering did not find it this way.
My guess is that even if we manage to get the `ParentEntry_ChildEntry.getData()` expression to work, it will break all existing templates, which were created before, with `ParentEntry.ChildEntry.getData()` expression.

What do you think, what would be the best solution?

Thanks,
Vendel

**Comment by pavel-savinov** [comment]
Hi @vendeltoreki, yes, you are right, I tried different ways and it doesn't work well for some cases. I'm going to send it to Brian, thanks!

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68935.

**Pull request closed without merging**
