### PR TITLE
LPS-79592 Editable fields allow invalid content in "type" attribute

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1575. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/d8d82d2~1...d8d82d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
