### PR TITLE
LPS-105951 Simplify assertions

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82259. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/8be36f37764d~1...8be36f37764d)

**Pull request closed without merging**
