### PR TITLE
LPS-82798 Some layouts must be wrapped and some others not so this condition is not valid if Layout is of type Content

### PR DESCRIPTION
**Pull request by dacousalr**
I have tried to keep a single layout revision per Content Page and per Site Pages variation but that approach did not seem to be very suitable, so the chosen approach was to not mark Content Pages as branching layouts. Thanks in advance

\cc @ericyanLr @jordirodo

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ericyanLr** [comment]
Hi @pavel-savinov ,

Was wondering if you had any updates for this pr review.
Thanks!

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81916.

**Pull request closed without merging**
