### PR TITLE
LPS-122134

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/95790

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2858. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/2e2d93505470~2...2e2d93505470)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2860. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/d03f74af2ff4~1...d03f74af2ff4)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2861. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/d957cc109b93~2...d957cc109b93)

**Pull request closed without merging**
