### PR TITLE
LPS-98038 | Deactivating staging breaks connection between fragment entry links and fragment entries

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @pavel-savinov. 

Please let me know if you have any questions or if you believe a better alternative is available. 

Thanks! 

/cc @jkappler

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Hi @pavel-savinov,

Would you mind having a look at this pr when you have the time? 

Thanks!

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75754.

**Pull request closed without merging**
