### PR TITLE
LPS-84606 Added condition to show the product menu only if the request has not the isolated property set to true

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62705. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
