### PR TITLE
LPS-119582

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/94219

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2333. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/5087c8dfabd8~1...5087c8dfabd8)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2336. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/51acc5c294c2~1...51acc5c294c2)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2373. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/9ad8c4e62eca~1...9ad8c4e62eca)

**Pull request closed without merging**
