### PR TITLE
[TS] LPS-110951

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> <https://issues.liferay.com/browse/LPS-110951>
> 
> The issue was that any basic component that uses color palettes would display a color CSS class in its HTML when no color was set. The expected behavior is that the color CSS class should not appear in the HTML (see [PTR-1597](https://issues.liferay.com/browse/PTR-1597)). To resolve this issue, I update the `index.js` for each component and remove the color CSS class when there is a 'hanging' dash symbol (which would suggest that no color has been selected). The issue affects the Separator, Heading, and Paragraph basic components. 
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/565. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/8b40f9de7c42~1...8b40f9de7c42)

**Pull request closed without merging**
