### PR TITLE
LPS-74570 Use SessionMessages from within our example portlet

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @pavel-savinov, 

I was reviewing https://github.com/brunobasto/liferay-portal/pull/870 and I noticed just removing MultiSessionMessages from the clear method fixes the issue. From Soy portlets we need to clear the messages after displaying it cause, since we don't use jsps, we don't leverage the default clear mechanism.

Let me know what you think. If this really fixes the issue you were having, can forward this PR to Brian?

Thx

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @brunobasto,

The problem with this _clearSessionMessages() is that we clear shared session which belongs not only to this portlet, but to all portlets on the page. For example, if PortletA puts something in SessionErrors or SessionMessages(which is quite common thing), PortletB(extends SoyPortlet) will remove it. And in this case only rendering order(user-defined) could save us from losing our session error or message.
We should try to find another solution, I'll ping you later on Slack.

Thanks!

**Comment by brunobasto** [comment]
Hey Pavel, I have tested and the problem described on the ticket goes away. From my understanding of the SessionMessages.java code, it scopes session message maps per portlet when it gets passed a PortletRequest instead of a HttpServlet request: https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/servlet/SessionMessages.java#L377

Let´s chat on slack

Thx

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51656. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51919. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
