### PR TITLE
LPS-78130 Fragment Collections cannot be imported

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1461. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/6875015~5...6875015) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1462. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/b31f8fe~6...b31f8fe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
