### PR TITLE
LPS-84004 Required validator added to Title and error checking added to form

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62276. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/c520359~2...c520359) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
