### PR TITLE
LPS-74630 Large tags field error publishing

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51519. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:reopen

**Pull request closed without merging**
