### PR TITLE
LPS-88008 Control Panel not being displayed when selecting locale with "-" in the URL

### PR DESCRIPTION
**Pull request by stsquared99**
Hi @pavel-savinov, sorry for the resend. I realized that I should not be touching the path when it is using the language code (en, as opposed to the language id, en_US). Please review for me. Thanks!

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66506. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
