### PR TITLE
LPS-98560 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76267. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/ea57e8e42250~5...ea57e8e42250)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76311. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/c3b878bd0030~6...c3b878bd0030)

**Pull request closed without merging**
