### PR TITLE
LPS-121109 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-121109

This is only for master.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2449. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/96dd10a3cb8a~1...96dd10a3cb8a)

**Pull request closed without merging**
