### PR TITLE
LPS-72193 FriendlyURLEntryLocalization

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @pavel-savinov,

if you're okay with these changes and I did not break anything can you send it to @shuyangzhou?  If I broke something or it's wrong somehow let me know.

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@pavel-savinov can you fix the DataFactory to also insert the FriendlyURLMapping?

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/4400. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/ece474e~1...ece474e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/4401. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/9976ff9~1...9976ff9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
