### PR TITLE
LPS-96245 | Imported document within fragment cannot be seen

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @pavel-savinov, 

I'm using the existing methods in DLReferencesExportImportContentProcessor to process url references to documents. 

Please let me know if you have any questions. Thanks! 

cc @jkappler

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74728.

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74729. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/474b63011333~1...474b63011333)

**Pull request closed without merging**
