### PR TITLE
LPS-102948 Test converting widget pages with layout template 3_2_3_columns with a multiple portlets per column

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79438.

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79479. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/31cb3ea1b4a7~1...31cb3ea1b4a7)

**Pull request closed without merging**
