### PR TITLE
LPS-105109

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@victorg1991 reviewed this :smile:

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2654. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/e9dfbadff1c6~3...e9dfbadff1c6)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82328. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/c4c668d43197~4...c4c668d43197)

**Pull request closed without merging**
