### PR TITLE
LPS-118979 As a page editor I would like to more easily identify the fields available when mapping an editable

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Please review and check the result with Juan Antón

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
Hey Pavel, it'll be necessary to adapt that test that is failing. Could you take care of that?

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1870. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/d6ec6a8890f9~1...d6ec6a8890f9)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1886. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/c94d7d58ef9f~2...c94d7d58ef9f)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1899. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/b40d2ac741d3~3...b40d2ac741d3)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1905. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/74d63d15ba7b~3...74d63d15ba7b)

**Pull request closed without merging**
