### PR TITLE
LPS-114877 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/638. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/a4a6e42e70c8~3...a4a6e42e70c8)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/827. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/4dcf25dc88ab~1...4dcf25dc88ab)

**Pull request closed without merging**
