### PR TITLE
LPS-67367-WIP

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @pavel-savinov,

Original Ticket: [LPP-23910](https://issues.liferay.com/browse/LPP-23910)
LPS Ticket: [LPS-67367](https://issues.liferay.com/browse/LPS-67367)

Support Forum Post: [Nested Portlet does not properly handle requests for inner portlets](https://in.liferay.com/web/support/forums/-/message_boards/view_message/29024829)

## Current Status
Here is a working solution for the current issue. But, I am still considering this as a WIP, since I am uncertain of the current implementation of the solution.

## Main Goal
The main goal of the changes to [PortalImpl.java](https://github.com/pavel-savinov/liferay-portal/commit/3e8a7519ebd1f186ef0063e14c82de631ca10aeb) is to provide a way to retrieve the original **FORWARD** request instead of the actual original servlet request.  

The reason is to preserve the parameters created by the FriendlyURLServlet.

Currently, we are passing the original servlet request, which does not provide the parameters generated by the FriendlyURLServlet.  This causes the nested portlets to not behave as expected when friendly urls are used.

## Next Steps / Questions

**getOriginalServletRequest(HttpServletRequest request, boolean forwardRequest) {**
- Do you think this is a good approach to implement our solution or should we create a separate method to handle this?
- Can you verify if my logic is correct on how the method is retrieving the original forward request?

**Adding a method to Portal.java/PortalImpl.java/PortalUtil.java**
- I am not sure if I am properly adding the new method to Portal.

----

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
It seems to be good approach! Thanks.
Sent to Brian, see https://github.com/brianchandotcom/liferay-portal/pull/46359

**Comment by ericyanLr** [comment]
Hi @pavel-savinov,

Just wanted to confirm, if you thought the logic to pin-point the last forward request is a good approach.
Reference: https://github.com/pavel-savinov/liferay-portal/pull/70/commits/3e8a7519ebd1f186ef0063e14c82de631ca10aeb#diff-97d14104465a5b7ecb93c57d8ffbb75aR3710

Would it be better to change it to:
`(nextRequest.getDispatcherType() != DispatcherType.FORWARD)) {`

Or do you think the original logic should be okay?
I'm actually not too familiar with the usual flow of requests in Liferay.

Just wanted to confirm, since the pr is at Brian.
Thanks!

**Edit:**
Discussed with Pavel, and the original approach looks okay, resolves the issue, does not break any tests, and would currently only be used by the nested portlets.

**Pull request closed without merging**
