### PR TITLE
LPS-105110

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81797

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81802. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/23dfaaf4d2fc~1...23dfaaf4d2fc)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81856. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/6de8112d14fa~2...6de8112d14fa)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81858. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/e51d0435bdf8~2...e51d0435bdf8)

**Pull request closed without merging**
