### PR TITLE
[TECHNICAL SUPPORT] LPS-89116 Friendly URL valiadtion

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @pavel-savinov ,

In commit https://github.com/pavel-savinov/liferay-portal/commit/07af32ce02faf0f41dbb6ae8dfa9883e3ac311d9 , I modified the friendly URL validation, to transform `urlTtitle` the same way as in [_updateFriendlyURLEntryLocalizations(..)](https://github.com/liferay/liferay-portal/blob/7ad30b4b124d72910ddd2b9eded34275ef9d0892/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L521) method. This way we can avoid discrepancies between the actual update and the validation methods.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/244. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/1b520e093668~1...1b520e093668)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67477.

**Pull request closed without merging**
