### PR TITLE
LPS-89483 Adds fragment structure and entries

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67582. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/89c130f14e48~3...89c130f14e48)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67590. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/265edc2051a9~4...265edc2051a9)

**Pull request closed without merging**
