### PR TITLE
LPS-107685 Return null if parts is empty

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84320. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/6138c91dee19~2...6138c91dee19)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84321. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/57c70c0b637a~2...57c70c0b637a)

**Pull request closed without merging**
