### PR TITLE
LPS-100414 Don't add new line when adding [#ftl] tag so line numbers in error messages are correct if Freemarker errors are found.

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77572. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/ef8e83570dbf~1...ef8e83570dbf)

**Pull request closed without merging**
