### PR TITLE
LPS-96705 Baseline

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74994. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/40d5fbb183b7~4...40d5fbb183b7)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75017. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/d9ac38202536~5...d9ac38202536)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75090. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/3e26a969966b~5...3e26a969966b)

**Pull request closed without merging**
