### PR TITLE
LPS-102813 Use objectToFormData to create form datas

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79292. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/44899103edb3~2...44899103edb3)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79293. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/44899103edb3~2...44899103edb3)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79294. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/321f7f7747bf~3...321f7f7747bf)

**Pull request closed without merging**
