### PR TITLE
LPS-94792 SF

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72756. [See changes here.](https://github.com/pavel-savinov/liferay-portal/compare/bc530bddb464~1...bc530bddb464)

**Pull request closed without merging**
